name: Bash CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - uses: mfinelli/setup-imagemagick@v6

    - name: check for imagemagick binaries
      run: which magick && which identify

    - name: Check for basic execution
      run: bash splashmark.sh

    - name: Test basic functioning
      run: tests/bash_unit tests/test_basic.sh

    - name: Test Image Effects
      run: tests/bash_unit tests/test_effects.sh

    - name: Test Providers (Unsplash/Pixabay/Replicate)
      run: tests/bash_unit tests/test_modes.sh

    - name: Test Preset Sizes
      run: tests/bash_unit tests/test_sizes.sh

